// Branch : supported_locations_resources_crud ->  create_supported_locations_front_end
enum SectionName {
  mutUmlaziDurbanKwaZuluNatalSouthAfrica,
  hawardCollegeCampusUKZNDurbanKwaZuluNatalSouthAfrica,
  westvilleCampusUKZNDurbanKwaZuluNatalSouthAfrica,
  edgewoodCampusUKZNPinetownKwaZuluNatalSouthAfrica,
  steveBikoCampusDutDurbanKwaZuluNatalSouthAfrica,

  catoCrestMayvilleDurbanKwaZuluNatalSouthAfrica,
  catoManorMayvilleDurbanKwaZuluNatalSouthAfrica,
  dunbarMayvilleDurbanKwaZuluNatalSouthAfrica,
  masxhaMayvilleDurbanKwaZuluNatalSouthAfrica,
  bonelaMayvilleDurbanKwaZuluNatalSouthAfrica,
  sherwoodMayvilleDurbanKwaZuluNatalSouthAfrica,
  richviewMayvilleDurbanKwaZuluNatalSouthAfrica,
  nsimbiniMayvilleDurbanKwaZuluNatalSouthAfrica,
  manorGardensMayvilleDurbanKwaZuluNatalSouthAfrica,
}
