// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6YytTl6G5v36_NXQEMBlCchkgAh-kpIo',
    appId: '1:12105173009:web:449a23487dd3426f6c09b0',
    messagingSenderId: '12105173009',
    projectId: 'alcoholic-expressions',
    authDomain: 'alcoholic-expressions.firebaseapp.com',
    storageBucket: 'alcoholic-expressions.appspot.com',
    measurementId: 'G-6TD8K84EF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0lxUDKf6puOBlnSCZd4agK8LWHu_7hMo',
    appId: '1:12105173009:android:3cd1f5c41a2d800f6c09b0',
    messagingSenderId: '12105173009',
    projectId: 'alcoholic-expressions',
    storageBucket: 'alcoholic-expressions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2twc4hJoWynn9yJXZQbfOb1bGj7HjlnY',
    appId: '1:12105173009:ios:5221fc913192d9896c09b0',
    messagingSenderId: '12105173009',
    projectId: 'alcoholic-expressions',
    storageBucket: 'alcoholic-expressions.appspot.com',
    iosBundleId: 'com.example.alcoholic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2twc4hJoWynn9yJXZQbfOb1bGj7HjlnY',
    appId: '1:12105173009:ios:5221fc913192d9896c09b0',
    messagingSenderId: '12105173009',
    projectId: 'alcoholic-expressions',
    storageBucket: 'alcoholic-expressions.appspot.com',
    iosBundleId: 'com.example.alcoholic',
  );
}
